/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RegisterImport } from './routes/register'
import { Route as LoginImport } from './routes/login'
import { Route as BoardsImport } from './routes/boards'
import { Route as BoardsIdImport } from './routes/boards.$id'

// Create/Update Routes

const RegisterRoute = RegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const BoardsRoute = BoardsImport.update({
  id: '/boards',
  path: '/boards',
  getParentRoute: () => rootRoute,
} as any)

const BoardsIdRoute = BoardsIdImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BoardsRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/boards': {
      id: '/boards'
      path: '/boards'
      fullPath: '/boards'
      preLoaderRoute: typeof BoardsImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/boards/$id': {
      id: '/boards/$id'
      path: '/$id'
      fullPath: '/boards/$id'
      preLoaderRoute: typeof BoardsIdImport
      parentRoute: typeof BoardsImport
    }
  }
}

// Create and export the route tree

interface BoardsRouteChildren {
  BoardsIdRoute: typeof BoardsIdRoute
}

const BoardsRouteChildren: BoardsRouteChildren = {
  BoardsIdRoute: BoardsIdRoute,
}

const BoardsRouteWithChildren =
  BoardsRoute._addFileChildren(BoardsRouteChildren)

export interface FileRoutesByFullPath {
  '/boards': typeof BoardsRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/boards/$id': typeof BoardsIdRoute
}

export interface FileRoutesByTo {
  '/boards': typeof BoardsRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/boards/$id': typeof BoardsIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/boards': typeof BoardsRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/boards/$id': typeof BoardsIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/boards' | '/login' | '/register' | '/boards/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/boards' | '/login' | '/register' | '/boards/$id'
  id: '__root__' | '/boards' | '/login' | '/register' | '/boards/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  BoardsRoute: typeof BoardsRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

const rootRouteChildren: RootRouteChildren = {
  BoardsRoute: BoardsRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/boards",
        "/login",
        "/register"
      ]
    },
    "/boards": {
      "filePath": "boards.tsx",
      "children": [
        "/boards/$id"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/boards/$id": {
      "filePath": "boards.$id.tsx",
      "parent": "/boards"
    }
  }
}
ROUTE_MANIFEST_END */
